[package]
name = "asms-batch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asms = { path = "../" }
tokio = { version = "1.21.0", features = ["rt-multi-thread", "macros"] }
